[package]
name = "mathlib-project"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "56f4cd1ef396e9fd389b5d8371ee9ad91d163625"}
